services:
  db:
      image: postgres
      container_name: postgres
      labels:
        app: tdt
      command: "postgres -c 'max_connections=500'"
      environment:
        ENV: dev
        PGUSER: postgres
        POSTGRES_DB: subject-db
        POSTGRES_USER: subject
        POSTGRES_PASSWORD: password
        DD_SERVICE: subject-api
        DD_VERSION: v1
      ports:
      - "5432:5432"      
      volumes:
        - ./init:/docker-entrypoint-initdb.d
