services:
  db:
      image: postgres
      container_name: postgres
      labels:
        app: tdt
      command: "postgres -c 'max_connections=500'"
      environment:
        ENV: dev
        POSTGRES_DB: subject-db
        POSTGRES_USER: subject
        POSTGRES_PASSWORD: password
        DD_SERVICE: subject-api
        DD_VERSION: v1
      ports:
      - "5432:5432"      
      # volumes:
      #   - shared_data:/shared_data
        # - ./init_datadog.sql:/docker-entrypoint-initdb.d/init_datadog.sql
# volumes:
#   shared_data:
