services:
  db:
      image: postgres
      container_name: postgres
      restart: always
      labels:
        app: tdt
      command: "postgres -c 'max_connections=500'"
      environment:
<<<<<<< HEAD
        
        PGUSER: subject
=======
        ENV: dev
        PGUSER: postgres
>>>>>>> f4141aad2aff907e61b093827683f6b3961166ec
        POSTGRES_DB: subject-db
        POSTGRES_USER: subject
        POSTGRES_PASSWORD: password
        DD_SERVICE: subject-api
        DD_VERSION: v1
        DD_ENV: tdt

      ports:
      - "5432:5432"      
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  pgdata:
