services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: with-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    volumes:
      - sqlserver_data:/var/opt/mssql
    platform: linux/amd64

volumes:
  sqlserver_data:
    driver: local
